### ISSUE TITLE
Link to userscript is outdated

### ISSUE THREAD

**Issue by athityakumar** [Daiz/GitHub-LiveMarkdown#24]
I know that this repo is actually quite old, with the last activity being 4 years ago. I'm just curious whether it still works. Anyways, mentioning the correct link to the userscript file will help in checking it out.

**Comment by vendethiel** [comment]
It stopped working around 2 years ago, if I recall correctly.

**Comment by athityakumar** [comment]
@vendethiel - Oh, bummer. Kindly let me know if you have come across an alternative that works. 😄
